# render.yaml

services:
  # 1. Flask 웹 애플리케이션 서비스
  - type: web
    name: wealth-tracker-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromDatabase:
          name: wealth-tracker-db # 아래 'databases'에 정의된 이름과 일치
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: wealth-tracker-redis # 아래 Redis 서비스에 정의된 이름과 일치
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true

  # 2. 백그라운드 워커 서비스
  - type: worker
    name: wealth-tracker-worker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "rq worker wealth-tracker-tasks"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromDatabase:
          name: wealth-tracker-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: wealth-tracker-redis
          property: connectionString
      - key: SESSION_SECRET
        fromService:
          type: web
          name: wealth-tracker-app
          envVarKey: SESSION_SECRET

  # 3. Redis 서비스
  - type: redis
    name: wealth-tracker-redis
    plan: free
    ipAllowList: [] # Render 내부 네트워크에서만 접속
    maxmemoryPolicy: allkeys-lru

databases:
  # 4. PostgreSQL 데이터베이스 (MySQL 대신 사용)
  - name: wealth-tracker-db
    plan: free
    # PostgreSQL의 경우, Render가 databaseName과 user를 자동으로 생성해주므로
    # 명시하지 않아도 됩니다.
