# render.yaml (PostgreSQL 최종 버전)

services:
  # 1. Flask 웹 애플리케이션 서비스
  - type: web
    name: wealth-tracker-app
    env: python
    plan: free # 무료 플랜 명시
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromDatabase:
          name: wealth-tracker-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: wealth-tracker-redis
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true

  # 2. 백그라운드 워커 서비스
  - type: worker
    name: wealth-tracker-worker
    env: python
    plan: free # 무료 플랜 명시
    buildCommand: "pip install -r requirements.txt"
    startCommand: "rq worker wealth-tracker-tasks"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromDatabase:
          name: wealth-tracker-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: wealth-tracker-redis
          property: connectionString
      - key: SESSION_SECRET
        fromService:
          type: web
          name: wealth-tracker-app
          envVarKey: SESSION_SECRET

  # 3. Redis 서비스
  - type: redis
    name: wealth-tracker-redis
    plan: free # 무료 플랜 명시

databases:
  # 4. PostgreSQL 데이터베이스
  - name: wealth-tracker-db
    plan: free # 무료 플랜 명시
    # databaseType: postgresql # 명시적으로 타입을 지정해 줄 수도 있습니다.
